INSERT INTO APP_TERMS( name, slug ) VALUES('검진', '%EA%B2%80%EC%A7%84');
INSERT INTO APP_TERMS( name, slug ) VALUES('생활', '%EC%83%9D%ED%99%9C');
INSERT INTO APP_TERMS( name, slug ) VALUES('생활', '%EC%83%9D%ED%99%9C');
INSERT INTO APP_TERMS( name, slug ) VALUES('식이', '%EC%8B%9D%EC%9D%B4');
INSERT INTO APP_TERMS( name, slug ) VALUES('약물', '%EC%95%BD%EB%AC%BC');
INSERT INTO APP_TERMS( name, slug ) VALUES('예방', '%EC%98%88%EB%B0%A9');
INSERT INTO APP_TERMS( name, slug ) VALUES('원인', '%EC%9B%90%EC%9D%B8');
INSERT INTO APP_TERMS( name, slug ) VALUES('재활', '%EC%9E%AC%ED%99%9C');
INSERT INTO APP_TERMS( name, slug ) VALUES('정의', '%EC%A0%95%EC%9D%98');
INSERT INTO APP_TERMS( name, slug ) VALUES('증상', '%EC%A6%9D%EC%83%81');
INSERT INTO APP_TERMS( name, slug ) VALUES('진단', '%EC%A7%84%EB%8B%A8');
INSERT INTO APP_TERMS( name, slug ) VALUES('치료', '%EC%B9%98%EB%A3%8C');
INSERT INTO APP_TERMS( name, slug ) VALUES('운동', '%EC%9A%B4%EB%8F%99');
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EA%B2%80%EC%A7%84'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%83%9D%ED%99%9C'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%83%9D%ED%99%9C'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%8B%9D%EC%9D%B4'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%95%BD%EB%AC%BC'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%98%88%EB%B0%A9'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%9B%90%EC%9D%B8'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%9E%AC%ED%99%9C'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%A0%95%EC%9D%98'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%A6%9D%EC%83%81'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%A7%84%EB%8B%A8'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%B9%98%EB%A3%8C'), 'intention', 0);
INSERT INTO APP_TERM_CATEGORY( term_id, category, parent ) VALUES((SELECT id FROM APP_TERMS WHERE slug='%EC%9A%B4%EB%8F%99'), 'intention', 0);
