/* 글 및 포스트(POSTS) 관련 테이블
*/
-- APP_POSTS
-- APP_POSTMETA 
-- APP_TERM_POST_RELATIONSHIPS

/* ----------------------------------------
 * 글(POSTS), app_posts
---------------------------------------- */

CREATE TABLE app_posts (

    id NUMBER(20, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    guid VARCHAR2(255) DEFAULT '' NOT NULL,
    
    post_title CLOB NOT NULL,
    post_content CLOB DEFAULT EMPTY_CLOB(),
    post_excerpt CLOB DEFAULT EMPTY_CLOB(),  
    post_name VARCHAR2(200) DEFAULT '' NULL,
    
    post_pass VARCHAR2(255) DEFAULT '' NOT NULL, 
    
    post_type VARCHAR2(100) DEFAULT 'post' NOT NULL,
    post_mime_type VARCHAR2(100) DEFAULT '' NULL,       

    post_author NUMBER(20, 0) DEFAULT 0 NOT NULL,
    post_parent NUMBER(20) DEFAULT 0 NOT NULL,   
    
    post_status VARCHAR2(20) DEFAULT 'publish' NOT NULL,    
    
    post_date TIMESTAMP DEFAULT TO_DATE('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    post_date_gmt TIMESTAMP DEFAULT TO_DATE('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    post_modified TIMESTAMP DEFAULT TO_DATE('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    post_modified_gmt TIMESTAMP DEFAULT TO_DATE('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
    
    comment_status VARCHAR2(20) DEFAULT 'open' NOT NULL CHECK (comment_status IN ('open', 'close')),
    comment_count NUMBER(20) DEFAULT 0 NOT NULL,
    menu_order NUMBER DEFAULT 0 NOT NULL,
    
    CONSTRAINT fk_posts_post_author FOREIGN KEY (post_author) REFERENCES app_users(id) 
    
);

CREATE INDEX i_app_posts_post_name ON app_posts(post_name);
CREATE INDEX i_app_posts_post_type ON app_posts(post_type);
CREATE INDEX i_app_posts_post_status ON app_posts(post_status);
CREATE INDEX i_app_posts_post_author ON app_posts(post_author);
CREATE INDEX i_app_posts_post_parent ON app_posts(post_parent);



/* ----------------------------------------
 * 글 메타(POSTMETA), app_postmeta
---------------------------------------- */
/* SEQUENCE & TRIGGER, app_postmeta.meta_id, CLOB */
-- CREATE OR REPLACE TRIGGER
CREATE OR REPLACE TRIGGER TRG_APP_POSTMETA_EMPTY_CLOB
BEFORE INSERT ON app_postmeta 
FOR EACH ROW 
BEGIN 
     IF :NEW.meta_value IS NULL THEN
        :NEW.meta_value := EMPTY_CLOB();
    END IF;     
END; 
/

CREATE TABLE app_postmeta (
    meta_id NUMBER(20, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id NUMBER(20, 0) DEFAULT 0 NOT NULL, 
    meta_key VARCHAR2(255),
    meta_value CLOB DEFAULT EMPTY_CLOB(),
    
    CONSTRAINT fk_app_postmeta_post_id FOREIGN KEY (post_id) REFERENCES app_posts(id) ON DELETE CASCADE
);

CREATE INDEX i_app_postmeta_post_id_meta_key ON app_postmeta ( post_id, meta_key ); 



/* ----------------------------------------
 * 용어와 글 관계(Term Post Relationship), app_term_post_relationships 
---------------------------------------- */

CREATE TABLE app_term_post_relationships (
    object_id NUMBER(20,0) NOT NULL,
    term_taxonomy_id NUMBER(20, 0) NOT NULL,
    term_order NUMBER DEFAULT 0 NOT NULL,
    
    CONSTRAINT fk_app_term_post_relationships_object_id FOREIGN KEY (object_id) REFERENCES app_posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_term_post_relationships_term_taxonomy_id FOREIGN KEY (term_taxonomy_id) REFERENCES app_term_taxonomy(term_taxonomy_id) ON DELETE CASCADE
);

CREATE INDEX i_app_term_post_relationships_object_id ON app_term_post_relationships(object_id);
CREATE INDEX i_app_term_post_relationships_term_taxonomy_id ON app_term_post_relationships(term_taxonomy_id);