/* by. SYSTEM (ROOT) Account 
*/

-- 현재 버전 확인 
SELECT * FROM PRODUCT_COMPONENT_VERSION;

-- 전체 사용자 계정 조회
SELECT USERNAME FROM ALL_USERS ORDER BY USERNAME;
-- DBA 권한이 있는 경우, 전체 사용자 계정 조회 
SELECT USERNAME FROM DBA_USERS ORDER BY USERNAME; 
-- + 계정 상태 
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS ORDER BY USERNAME;

-- DB 접속 가능한 사용자만 조회
SELECT USERNAME FROM DBA_USERS WHERE ACCOUNT_STATUS = 'OPEN' ORDER BY USERNAME;


-- Create new account 
-- QUOTA UNLIMITED ON USERS : Tablespace 내에서 무제한 이용 가능 
CREATE USER pys IDENTIFIED BY oracle
QUOTA UNLIMITED ON USERS;

-- Grant required permissions.
-- CONNECT : Connected perm 
-- RESOURCE : Managed tables perm
GRANT CONNECT, RESOURCE TO pys;

-- Grant Table and data-related permissions.
-- GRANT SELECT, INSERT, UPDATE, DELETE ON new_user.table_name TO new_user;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO pys;


